-- GENERATED by tools/build-migrations.mjs from supabase/reverts/. Do not edit — run
-- `npm run build:migrations` instead (instruction_mds/migrations.md).
--
-- DESTROYS DATA. Every revert, newest first, which takes the schema back to nothing. A migration
-- marked `-- no-revert:` has no block here.

-- ===== 20260930110000_sales.sql =====

-- Reverts 20260930110000_sales.sql.
--
-- DESTROYS DATA: every sale and sale line. The stock movements the sales made stay in the ledger, since
-- the ledger is append-only and the packs already reflect them. The Register and Receipts screens expect
-- these tables — src/features/sales and src/lib/database.types.ts — so regenerate the types after.

drop function if exists public.void_sale(uuid, text);
drop function if exists public.record_sale(jsonb);

drop index if exists public.stock_movements_ref_idx;

drop table if exists public.sale_lines;
drop table if exists public.sales;

delete from private.merchant_counters where kind = 'sale';


-- ===== 20260930100000_receipt_inputs.sql =====

-- Reverts 20260930100000_receipt_inputs.sql.
--
-- DESTROYS DATA: every lot's packs_expected and units_per_pack_received. The cost per base unit a
-- merchant typed stays on the lots already saved; only new receipts go back to spreading freight.
--
-- FAILS while any receipt has no supplier or any lot has no lot number: the not null constraints cannot
-- come back over those rows. Give them a supplier and a lot number, or void and remove them, first.
--
-- Run this before 20260929100100_stock_ledger.sql's revert (instruction_mds/migrations.md rule 6), and
-- regenerate src/lib/database.types.ts after.

-- One lot, its cases and a row per pack, and a receive movement per pack. Shared by save_receipt,
-- add_inventory_stock and §7. The caller has locked the item and checked membership.
--
-- p_line: { cases?, packs_per_case?, cost_per_case?, case_sscc?, packs?, cost_per_pack?, loose_units?,
--           unit_loads?, pallets_per_unit_load?, unit_load_sscc?, pallets?, cases_per_pallet?,
--           pallet_sscc?, lot_code?, expires_on?, location?, notes?, serials?: text[] }
create or replace function private.create_lot(
  p_item public.products, p_receipt public.stock_receipts, p_position integer, p_line jsonb
)
returns public.stock_lots
language plpgsql
set search_path = ''
as $$
declare
  v_merchant uuid := p_item.merchant_id;
  v_on date := coalesce(p_receipt.received_on, current_date);
  v_upp numeric := coalesce(p_item.conversion_factor, 1);
  v_cases integer := nullif((p_line ->> 'cases')::integer, 0);
  v_per_case integer;
  v_packs integer;
  v_loose numeric := coalesce((p_line ->> 'loose_units')::numeric, 0);
  v_cost numeric;
  v_serials text[];
  v_lot public.stock_lots;
  v_case_id uuid;
  v_pack public.stock_packs;
  v_n integer := 0;
  i integer;
  j integer;
begin
  -- Case tier: cost is entered per case, and the pack cost follows.
  if v_cases is not null then
    v_per_case := (p_line ->> 'packs_per_case')::integer;
    if coalesce(v_per_case, 0) <= 0 or (p_line ->> 'cost_per_case') is null then
      raise exception 'receipt_line_case_tier' using errcode = '23514';
    end if;
    v_packs := v_cases * v_per_case;
    v_cost := (p_line ->> 'cost_per_case')::numeric / v_per_case;
  else
    v_packs := coalesce((p_line ->> 'packs')::integer, 0);
    v_cost := coalesce((p_line ->> 'cost_per_pack')::numeric, coalesce(p_item.cost_price, 0) * v_upp);
  end if;

  if v_packs < 0 or v_loose < 0 or v_loose >= v_upp or v_packs * v_upp + v_loose <= 0 then
    raise exception 'receipt_line_quantity' using errcode = '23514';
  end if;

  -- Has expiry: a received line needs its date. An Inventory add may leave it blank.
  if p_receipt.id is not null and p_item.perishable and (p_line ->> 'expires_on') is null then
    raise exception 'receipt_line_expiry_required' using errcode = '23514';
  end if;

  select coalesce(array_agg(btrim(s.serial) order by s.ord), '{}') into v_serials
  from jsonb_array_elements_text(coalesce(p_line -> 'serials', '[]')) with ordinality as s (serial, ord)
  where btrim(s.serial) <> '';
  if cardinality(v_serials) > v_packs then
    raise exception 'receipt_line_serial_count'
      using errcode = '23514', detail = 'More serial numbers than packs.';
  end if;

  -- issue_code only runs when no lot number was typed, so a typed one never burns a counter value.
  insert into public.stock_lots (
    merchant_id, source, receipt_id, position, product_id, code, units_per_pack,
    unit_loads, pallets_per_unit_load, unit_load_sscc, pallets, cases_per_pallet, pallet_sscc,
    cases, packs_per_case, cost_per_case, case_sscc,
    packs_received, loose_units, cost_per_pack, expires_on, location, notes
  ) values (
    v_merchant, case when p_receipt.id is null then 'inventory' else 'stock' end::public.stock_lot_source,
    p_receipt.id, p_position, p_item.id,
    coalesce(
      nullif(btrim(p_line ->> 'lot_code'), ''),
      private.issue_code(v_merchant, 'lot', 'LOT-' || to_char(v_on, 'YYYYMMDD') || '-', 3, 'public.stock_lots', 'code')
    ),
    v_upp,
    nullif((p_line ->> 'unit_loads')::integer, 0), nullif((p_line ->> 'pallets_per_unit_load')::integer, 0),
    nullif(btrim(p_line ->> 'unit_load_sscc'), ''),
    nullif((p_line ->> 'pallets')::integer, 0), nullif((p_line ->> 'cases_per_pallet')::integer, 0),
    nullif(btrim(p_line ->> 'pallet_sscc'), ''),
    v_cases, v_per_case, case when v_cases is not null then (p_line ->> 'cost_per_case')::numeric end,
    nullif(btrim(p_line ->> 'case_sscc'), ''),
    v_packs, v_loose, v_cost,
    (p_line ->> 'expires_on')::date,
    coalesce(nullif(btrim(p_line ->> 'location'), ''), p_receipt.location, p_item.storage_location),
    nullif(btrim(p_line ->> 'notes'), '')
  )
  returning * into v_lot;

  -- Packs in cases first, then loose packs, then the partial pack the loose units make.
  for i in 0 .. coalesce(v_cases, 0) loop
    v_case_id := null;
    if i > 0 then
      insert into public.stock_cases (merchant_id, lot_id, code, sscc)
      values (
        v_merchant, v_lot.id,
        private.issue_code(v_merchant, 'case', 'CS-', 4, 'public.stock_cases', 'code'),
        -- The one SSCC typed on the form labels the first case.
        case when i = 1 then v_lot.case_sscc end
      )
      returning id into v_case_id;
    end if;

    for j in 1 .. case when i = 0 then (case when v_cases is null then v_packs else 0 end) else v_per_case end loop
      v_n := v_n + 1;
      insert into public.stock_packs (merchant_id, product_id, lot_id, case_id, code, serial, units, qty_remaining)
      values (
        v_merchant, p_item.id, v_lot.id, v_case_id,
        private.issue_code(v_merchant, 'pack', 'PK-', 6, 'public.stock_packs', 'code'),
        v_serials[v_n], v_upp, v_upp
      )
      returning * into v_pack;

      insert into public.stock_movements (merchant_id, product_id, lot_id, pack_id, kind, qty, ref, created_by)
      values (v_merchant, p_item.id, v_lot.id, v_pack.id, 'receive', v_upp, coalesce(p_receipt.code, v_lot.code),
        (select auth.uid()));
    end loop;
  end loop;

  if v_loose > 0 then
    insert into public.stock_packs (merchant_id, product_id, lot_id, code, units, qty_remaining, opened_at)
    values (
      v_merchant, p_item.id, v_lot.id,
      private.issue_code(v_merchant, 'pack', 'PK-', 6, 'public.stock_packs', 'code'),
      v_upp, v_loose, now()
    )
    returning * into v_pack;

    insert into public.stock_movements (merchant_id, product_id, lot_id, pack_id, kind, qty, ref, created_by)
    values (v_merchant, p_item.id, v_lot.id, v_pack.id, 'receive', v_loose, coalesce(p_receipt.code, v_lot.code),
      (select auth.uid()));
  end if;

  -- No freight yet; save_receipt spreads it once every line is in.
  update public.stock_lots set unit_cost = line_cost / qty_received where id = v_lot.id
  returning * into v_lot;
  return v_lot;
end;
$$;

revoke execute on function private.create_lot(public.products, public.stock_receipts, integer, jsonb)
  from public, anon, authenticated, service_role;


-- save_receipt(payload): {
--   merchant_id, supplier_id, invoice_no?, received_on?, received_by?, location?, freight?, notes?,
--   lines: [{ product_id | new_item: { item, group_name? }, ...private.create_lot's p_line }]
-- }
-- Returns the receipt id. A saved receipt never changes; void_receipt and record_stock_movement make
-- the corrections.
create or replace function public.save_receipt(payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  r public.stock_receipts;
  v_merchant uuid := (payload ->> 'merchant_id')::uuid;
  v_supplier uuid := (payload ->> 'supplier_id')::uuid;
  v_freight numeric := coalesce((payload ->> 'freight')::numeric, 0);
  v_line jsonb;
  v_pos integer := 0;
  v_item public.products;
  v_item_id uuid;
  v_lot public.stock_lots;
  v_value_total numeric;
  v_qty_total numeric;
  v_left numeric;
  v_share numeric;
begin
  perform private.assert_member(v_merchant);

  if v_supplier is null or not exists (
    select 1 from public.suppliers s where s.id = v_supplier and s.merchant_id = v_merchant and s.active
  ) then
    raise exception 'supplier_not_available' using errcode = '23514';
  end if;
  if jsonb_array_length(coalesce(payload -> 'lines', '[]')) = 0 then
    raise exception 'receipt_has_no_lines' using errcode = '23514';
  end if;

  insert into public.stock_receipts (
    merchant_id, code, supplier_id, invoice_no, received_on, received_by, location, freight, notes, created_by
  ) values (
    v_merchant,
    private.issue_code(v_merchant, 'receipt', 'RC-', 4, 'public.stock_receipts', 'code'),
    v_supplier,
    nullif(btrim(payload ->> 'invoice_no'), ''),
    coalesce((payload ->> 'received_on')::date, current_date),
    nullif(btrim(payload ->> 'received_by'), ''),
    nullif(btrim(payload ->> 'location'), ''),
    v_freight,
    nullif(btrim(payload ->> 'notes'), ''),
    (select auth.uid())
  )
  returning * into r;

  for v_line in select e.value from jsonb_array_elements(payload -> 'lines') as e (value) loop
    v_pos := v_pos + 1;

    -- A new item is made inside the transaction, so an abandoned receipt leaves no orphan item.
    if v_line ? 'new_item' then
      v_item_id := public.save_stock_item(jsonb_build_object(
        'item', (v_line -> 'new_item' -> 'item') || jsonb_build_object('id', null, 'merchant_id', v_merchant),
        'group_name', v_line -> 'new_item' -> 'group_name'
      ));
    else
      v_item_id := (v_line ->> 'product_id')::uuid;
    end if;

    select * into v_item from public.products
    where id = v_item_id and merchant_id = v_merchant and type = 'stock' and status <> 'archived'
    for update;
    if v_item.id is null then
      raise exception 'stock_item_not_found' using errcode = 'P0002';
    end if;

    perform private.create_lot(v_item, r, v_pos, v_line);
  end loop;

  -- Freight: spread by line value, or by quantity when every line cost nothing. The last line takes
  -- what rounding leaves, so the shares add up to the freight exactly.
  select coalesce(sum(l.line_cost), 0), coalesce(sum(l.qty_received), 0) into v_value_total, v_qty_total
  from public.stock_lots l where l.receipt_id = r.id;
  v_left := v_freight;

  for v_lot in select * from public.stock_lots l where l.receipt_id = r.id order by l.position loop
    v_share := case
      when v_lot.position = v_pos then v_left
      when v_value_total > 0 then round(v_freight * v_lot.line_cost / v_value_total, 2)
      else round(v_freight * v_lot.qty_received / v_qty_total, 2)
    end;
    v_left := v_left - v_share;

    update public.stock_lots
    set freight_share = v_share, unit_cost = (v_lot.line_cost + v_share) / v_lot.qty_received
    where id = v_lot.id;
  end loop;

  perform private.recompute_stock(l.product_id)
  from (select distinct product_id from public.stock_lots where receipt_id = r.id) l;

  return r.id;
end;
$$;

revoke execute on function public.save_receipt(jsonb) from public, anon, authenticated, service_role;
grant execute on function public.save_receipt(jsonb) to authenticated;

alter table if exists public.stock_lots drop constraint if exists stock_lots_expected_positive;
alter table if exists public.stock_lots drop column if exists units_per_pack_received;
alter table if exists public.stock_lots drop column if exists packs_expected;
alter table if exists public.stock_lots alter column code set not null;

alter table if exists public.stock_receipts alter column supplier_id set not null;


-- ===== 20260929100100_stock_ledger.sql =====

-- Reverts 20260929100100_stock_ledger.sql.
--
-- DESTROYS DATA: every receipt, lot, case, pack and serial, and the whole stock ledger. Each item's
-- qty_on_hand and cost_price stay at their last computed values and become plain editable columns again,
-- so what is on hand survives as a number with no lot, expiry or history behind it. Re-applying turns
-- those numbers back into Inventory-added stock.
--
-- Run this before 20260929100000_stock_items.sql's revert (instruction_mds/migrations.md rule 6). The app
-- expects the new shape — src/features and src/lib/database.types.ts — so regenerate the types after.

drop function if exists public.void_receipt(uuid, text);
drop function if exists public.record_stock_movement(jsonb);
drop function if exists public.draw_stock(jsonb);
drop function if exists public.add_inventory_stock(jsonb);
drop function if exists public.save_receipt(jsonb);
drop function if exists private.create_lot(public.products, public.stock_receipts, integer, jsonb);
drop function if exists private.recompute_stock(uuid);

drop trigger if exists products_guard_stock on public.products;
drop function if exists private.guard_stock_item();

drop view if exists public.stock_pick_queue;
drop view if exists public.stock_lot_lines;

drop table if exists public.stock_movements;
drop table if exists public.stock_packs;
drop table if exists public.stock_cases;
drop table if exists public.stock_lots;
drop table if exists public.stock_receipts;

drop type if exists public.stock_lot_source;
drop type if exists public.write_off_reason;
drop type if exists public.stock_movement_kind;


-- ===== 20260929100000_stock_items.sql =====

-- Reverts 20260929100000_stock_items.sql.
--
-- DESTROYS DATA: every product group, and each product's pack and base unit names, Sell By, role,
-- group, attributes and face link. Faces that never got a category are deleted (their component rows go
-- with them), because category_id becomes required again. Generated SKUs stay: sku is an older column,
-- and a SKU is never taken back.
--
-- Fails on purpose while a stock item has no category: give it one first rather than lose the item.
--
-- Run 20260929100100_stock_ledger.sql's revert first (instruction_mds/migrations.md rule 6). The app
-- expects the new shape — src/features/products and src/lib/database.types.ts — so regenerate the types
-- after running this.

drop function if exists public.save_stock_item(jsonb);
drop trigger if exists products_sync_register_faces on public.products;
drop function if exists private.sync_register_faces();
drop function if exists public.ensure_register_faces(uuid);
drop trigger if exists products_assign_sku on public.products;

delete from public.products where source_item_id is not null and category_id is null;

alter table if exists public.products drop constraint if exists products_stock_fields;
alter table if exists public.products drop constraint if exists products_category_required;
alter table if exists public.products alter column category_id set not null;

alter table if exists public.products drop constraint if exists products_unit_names_length;
alter table if exists public.products drop constraint if exists products_source_item_fk;
alter table if exists public.products drop constraint if exists products_group_fk;

alter table if exists public.products
  drop column if exists source_item_id,
  drop column if exists attributes,
  drop column if exists group_id,
  drop column if exists stock_role,
  drop column if exists sell_by,
  drop column if exists base_unit_name,
  drop column if exists pack_unit_name;

drop table if exists public.product_groups;

drop type if exists public.stock_role;
drop type if exists public.stock_sell_by;


-- ===== 20260928100300_supplier_code_default.sql =====

-- Reverts 20260928100300_supplier_code_default.sql.
--
-- Destroys no data. Codes already issued stay. The app sends '' for a blank code, which this revert
-- turns into a failed insert (suppliers_details_length), so regenerate src/lib/database.types.ts and
-- have the form send a code after running it.

drop trigger if exists suppliers_assign_code on public.suppliers;
create trigger suppliers_assign_code
  before insert or update of code on public.suppliers
  for each row when (new.code is null)
  execute function private.assign_code('supplier', 'SUP-', '4', 'code');

alter table if exists public.suppliers alter column code drop default;


-- ===== 20260928100000_suppliers_extend.sql =====

-- Reverts 20260928100000_suppliers_extend.sql.
--
-- DESTROYS DATA: every supplier type, and each supplier's code, phone, email, address, payment terms,
-- type, lead time, TIN, active flag and notes. contact_person is renamed back to contact, so what it
-- holds survives. The code counters go too, so a re-apply starts SUP, SKU, RC and LOT numbering over.
--
-- Run 20260928100100_stock_items.sql's revert first: its SKU trigger calls private.assign_code()
-- (instruction_mds/migrations.md rule 6). The app expects the new shape — src/features/suppliers and
-- src/lib/database.types.ts — so regenerate the types after running this.

drop trigger if exists suppliers_assign_code on public.suppliers;

alter table if exists public.suppliers drop constraint if exists suppliers_lead_time_non_negative;
alter table if exists public.suppliers drop constraint if exists suppliers_details_length;
alter table if exists public.suppliers drop constraint if exists suppliers_code_unique;
alter table if exists public.suppliers drop constraint if exists suppliers_type_fk;

alter table if exists public.suppliers
  drop column if exists notes,
  drop column if exists active,
  drop column if exists tin,
  drop column if exists lead_time_days,
  drop column if exists supplier_type_id,
  drop column if exists payment_terms,
  drop column if exists address,
  drop column if exists email,
  drop column if exists phone,
  drop column if exists code;

do $$
begin
  if exists (select 1 from pg_constraint where conname = 'suppliers_contact_person_length') then
    alter table public.suppliers rename constraint suppliers_contact_person_length to suppliers_contact_length;
  end if;
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'suppliers' and column_name = 'contact_person'
  ) then
    alter table public.suppliers rename column contact_person to contact;
  end if;
end
$$;

drop table if exists public.supplier_types;

drop function if exists private.assign_code();
drop function if exists private.assert_member(uuid);
drop function if exists private.issue_code(uuid, text, text, integer, regclass, text);
drop function if exists private.next_number(uuid, text);
drop table if exists private.merchant_counters;


-- ===== 20260917183630_resource_scopes.sql =====

-- Reverts 20260917120000_resource_scopes.sql.
--
-- Destroys data: only the scope of each category. Categories, products and stock counts all stay.
-- It fails on purpose if two Resources screens each hold a category with the same name under the same
-- parent. The old unique key allowed one name per parent across every screen; rename one before
-- reverting.
--
-- The app expects the scoped shape (src/features/products/resources.ts, the three Resources screens),
-- so regenerate src/lib/database.types.ts after running this.
--
-- Newest revert, so nothing has to run before it (instruction_mds/migrations.md rule 6).

drop trigger if exists set_product_scope on public.products;
drop function if exists private.set_product_scope();

alter table if exists public.products drop constraint if exists products_subcategory_fk;
alter table if exists public.products drop constraint if exists products_category_fk;
alter table if exists public.product_categories drop constraint if exists product_categories_name_unique;
alter table if exists public.product_categories drop constraint if exists product_categories_parent_fk;
alter table if exists public.product_categories drop constraint if exists product_categories_id_merchant_scope;

alter table if exists public.products drop column if exists scope;
alter table if exists public.product_categories drop column if exists scope;
drop type if exists public.category_scope;

-- Back to the keys 20260914092147_products.sql created.
alter table public.product_categories
  add constraint product_categories_parent_fk foreign key (parent_id, merchant_id)
    references public.product_categories (id, merchant_id) on delete cascade;
alter table public.product_categories
  add constraint product_categories_name_unique unique nulls not distinct (merchant_id, parent_id, name);
alter table public.products
  add constraint products_category_fk foreign key (category_id, merchant_id)
    references public.product_categories (id, merchant_id);
alter table public.products
  add constraint products_subcategory_fk foreign key (subcategory_id, merchant_id)
    references public.product_categories (id, merchant_id);

-- save_product as 20260914092147_products.sql wrote it: `type` writable again on update.
create or replace function public.save_product(payload jsonb)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  p public.products;
  v_id uuid;
  v_merchant uuid;
begin
  p := jsonb_populate_record(null::public.products, payload -> 'product');

  if p.id is null then
    insert into public.products (
      merchant_id, type, name, category_id, subcategory_id, sku, barcode, description, tags, status,
      sold_directly, selling_price, cost_price, pricing_unit, tax_class_id, discountable,
      deposit_amount, late_fee_per_hour, cancellation_fee, extra_unit_fee,
      uom, track_inventory, qty_on_hand, reorder_threshold, reorder_qty, max_stock, storage_location,
      supplier_id, supplier_item_code, lead_time_days, batch_tracking, perishable, shelf_life_days,
      expiry_date, expiry_alert_days, purchase_unit, usage_unit, conversion_factor,
      total_units, capacity_per_unit, duration_mode, default_start_time, default_end_time,
      min_duration, min_duration_unit, max_duration, max_duration_unit, buffer_minutes,
      advance_window_days, blackout_dates, overbooking_allowed,
      has_variants, is_composite, internal_notes
    ) values (
      p.merchant_id, p.type, p.name, p.category_id, p.subcategory_id, p.sku, p.barcode, p.description,
      coalesce(p.tags, '{}'), coalesce(p.status, 'draft'),
      coalesce(p.sold_directly, true), p.selling_price, p.cost_price, p.pricing_unit, p.tax_class_id,
      coalesce(p.discountable, true),
      p.deposit_amount, p.late_fee_per_hour, p.cancellation_fee, p.extra_unit_fee,
      p.uom, coalesce(p.track_inventory, true), p.qty_on_hand, p.reorder_threshold, p.reorder_qty,
      p.max_stock, p.storage_location,
      p.supplier_id, p.supplier_item_code, p.lead_time_days, coalesce(p.batch_tracking, false),
      coalesce(p.perishable, false), p.shelf_life_days,
      p.expiry_date, p.expiry_alert_days, p.purchase_unit, p.usage_unit, p.conversion_factor,
      p.total_units, p.capacity_per_unit, p.duration_mode, p.default_start_time, p.default_end_time,
      p.min_duration, p.min_duration_unit, p.max_duration, p.max_duration_unit, p.buffer_minutes,
      p.advance_window_days, coalesce(p.blackout_dates, '{}'), coalesce(p.overbooking_allowed, false),
      coalesce(p.has_variants, false), coalesce(p.is_composite, false), p.internal_notes
    )
    returning id, merchant_id into v_id, v_merchant;
  else
    -- merchant_id is deliberately not in the SET list: a product does not move between merchants, and
    -- its child rows' composite keys would refuse it anyway.
    update public.products set
      type = p.type, name = p.name, category_id = p.category_id, subcategory_id = p.subcategory_id,
      sku = p.sku, barcode = p.barcode, description = p.description, tags = coalesce(p.tags, '{}'),
      status = coalesce(p.status, 'draft'), sold_directly = coalesce(p.sold_directly, true),
      selling_price = p.selling_price, cost_price = p.cost_price, pricing_unit = p.pricing_unit,
      tax_class_id = p.tax_class_id, discountable = coalesce(p.discountable, true),
      deposit_amount = p.deposit_amount, late_fee_per_hour = p.late_fee_per_hour,
      cancellation_fee = p.cancellation_fee, extra_unit_fee = p.extra_unit_fee,
      uom = p.uom, track_inventory = coalesce(p.track_inventory, true), qty_on_hand = p.qty_on_hand,
      reorder_threshold = p.reorder_threshold, reorder_qty = p.reorder_qty, max_stock = p.max_stock,
      storage_location = p.storage_location, supplier_id = p.supplier_id,
      supplier_item_code = p.supplier_item_code, lead_time_days = p.lead_time_days,
      batch_tracking = coalesce(p.batch_tracking, false), perishable = coalesce(p.perishable, false),
      shelf_life_days = p.shelf_life_days, expiry_date = p.expiry_date,
      expiry_alert_days = p.expiry_alert_days, purchase_unit = p.purchase_unit,
      usage_unit = p.usage_unit, conversion_factor = p.conversion_factor,
      total_units = p.total_units, capacity_per_unit = p.capacity_per_unit,
      duration_mode = p.duration_mode, default_start_time = p.default_start_time,
      default_end_time = p.default_end_time, min_duration = p.min_duration,
      min_duration_unit = p.min_duration_unit, max_duration = p.max_duration,
      max_duration_unit = p.max_duration_unit, buffer_minutes = p.buffer_minutes,
      advance_window_days = p.advance_window_days, blackout_dates = coalesce(p.blackout_dates, '{}'),
      overbooking_allowed = coalesce(p.overbooking_allowed, false),
      has_variants = coalesce(p.has_variants, false), is_composite = coalesce(p.is_composite, false),
      internal_notes = p.internal_notes, updated_at = now()
    where id = p.id
    returning id, merchant_id into v_id, v_merchant;

    -- RLS filters an UPDATE rather than refusing it, so another merchant's id updates zero rows.
    if v_id is null then
      raise exception 'product_not_found' using errcode = 'P0002';
    end if;
  end if;

  delete from public.product_rate_tiers where product_id = v_id;
  delete from public.product_operating_hours where product_id = v_id;
  delete from public.product_variant_attributes where product_id = v_id;
  delete from public.product_variants where product_id = v_id;
  delete from public.product_components where product_id = v_id;
  delete from public.product_custom_fields where product_id = v_id;

  insert into public.product_rate_tiers (product_id, merchant_id, position, period, price, note)
  select v_id, v_merchant, (e.idx - 1)::smallint, x.period, x.price, x.note
  from jsonb_array_elements(coalesce(payload -> 'rate_tiers', '[]')) with ordinality as e (value, idx)
  cross join lateral jsonb_populate_record(null::public.product_rate_tiers, e.value) as x;

  insert into public.product_operating_hours (product_id, merchant_id, weekday, opens, closes)
  select v_id, v_merchant, x.weekday, x.opens, x.closes
  from jsonb_array_elements(coalesce(payload -> 'operating_hours', '[]')) as e (value)
  cross join lateral jsonb_populate_record(null::public.product_operating_hours, e.value) as x;

  insert into public.product_variant_attributes (product_id, merchant_id, position, name, "values")
  select v_id, v_merchant, (e.idx - 1)::smallint, x.name, x."values"
  from jsonb_array_elements(coalesce(payload -> 'variant_attributes', '[]')) with ordinality as e (value, idx)
  cross join lateral jsonb_populate_record(null::public.product_variant_attributes, e.value) as x;

  insert into public.product_variants (
    product_id, merchant_id, position, label, options, sku, barcode, price_delta, qty_on_hand
  )
  select v_id, v_merchant, (e.idx - 1)::smallint, x.label, x.options, x.sku, x.barcode,
    coalesce(x.price_delta, 0), x.qty_on_hand
  from jsonb_array_elements(coalesce(payload -> 'variants', '[]')) with ordinality as e (value, idx)
  cross join lateral jsonb_populate_record(null::public.product_variants, e.value) as x;

  insert into public.product_components (product_id, merchant_id, position, component_id, qty, unit)
  select v_id, v_merchant, (e.idx - 1)::smallint, x.component_id, x.qty, x.unit
  from jsonb_array_elements(coalesce(payload -> 'components', '[]')) with ordinality as e (value, idx)
  cross join lateral jsonb_populate_record(null::public.product_components, e.value) as x;

  insert into public.product_custom_fields (product_id, merchant_id, position, label, kind, value)
  select v_id, v_merchant, (e.idx - 1)::smallint, x.label, coalesce(x.kind, 'text'), x.value
  from jsonb_array_elements(coalesce(payload -> 'custom_fields', '[]')) with ordinality as e (value, idx)
  cross join lateral jsonb_populate_record(null::public.product_custom_fields, e.value) as x;

  return v_id;
end;
$$;

revoke execute on function public.save_product(jsonb) from public, anon, authenticated, service_role;
grant execute on function public.save_product(jsonb) to authenticated;


-- ===== 20260914092147_products.sql =====

-- Reverts 20260914000000_products.sql.
--
-- DESTROYS DATA: every product, category, tax class and supplier of every merchant, with all their
-- rate tiers, operating hours, variants, components and custom fields. merchants.currency goes too.
--
-- The app expects the new shape — src/features/products, src/features/categories,
-- src/features/tax-classes, src/features/suppliers and src/lib/database.types.ts all name it — so
-- regenerate the types after running this.
--
-- Newest revert, so nothing has to run before it (instruction_mds/migrations.md rule 6).

drop function if exists public.save_product(jsonb);

-- Dropping product_components takes its trigger with it; the function is dropped after the table.
drop table if exists public.product_custom_fields;
drop table if exists public.product_components;
drop table if exists public.product_variants;
drop table if exists public.product_variant_attributes;
drop table if exists public.product_operating_hours;
drop table if exists public.product_rate_tiers;
drop table if exists public.products;
drop table if exists public.suppliers;
drop table if exists public.tax_classes;
drop table if exists public.product_categories;

drop function if exists private.assert_no_bundle_cycle();

-- After the tables whose columns use them.
drop type if exists public.custom_field_kind;
drop type if exists public.rate_period;
drop type if exists public.duration_mode;
drop type if exists public.measure_unit;
drop type if exists public.product_status;
drop type if exists public.product_type;

alter table if exists public.merchants drop constraint if exists merchants_currency_shape;
alter table if exists public.merchants drop column if exists currency;

-- Back to how 20260908131200_merchants.sql left the seam: no caller, no grant.
do $$
begin
  if to_regprocedure('private.current_merchant_ids()') is not null then
    revoke execute on function private.current_merchant_ids() from authenticated;
  end if;
end
$$;
revoke usage on schema private from authenticated;


-- ===== 20260910000000_merchants_contact_and_address.sql =====

-- Reverts 20260910000000_merchants_contact_and_address.sql.
--
-- DESTROYS DATA: every merchant's contact_email and phone go with their columns. address is renamed
-- back to description, so what it holds survives.
--
-- The app expects the new shape — src/features/merchants/schema.ts and src/lib/database.types.ts
-- name all three columns — so regenerate the types after running this.
--
-- Newest revert, so nothing has to run before it. supabase/all-in-one/revert.sql orders every revert
-- newest first (instruction_mds/migrations.md).

-- Dropping a column takes its check constraint with it. Named anyway, so this file reads as the exact
-- inverse of the one it undoes.
alter table if exists public.merchants drop constraint if exists merchants_phone_shape;
alter table if exists public.merchants drop constraint if exists merchants_contact_email_shape;

alter table if exists public.merchants drop column if exists phone;
alter table if exists public.merchants drop column if exists contact_email;

-- Guarded by a catalog lookup for the same reason the forward rename is: ALTER ... RENAME COLUMN
-- accepts no `if exists`.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'merchants' and column_name = 'address'
  ) then
    alter table public.merchants rename column address to description;
    alter table public.merchants rename constraint merchants_address_length to merchants_description_length;
  end if;
end
$$;


-- ===== 20260908131200_merchants.sql =====

-- Reverts 20260908131200_merchants.sql.
--
-- DESTROYS DATA: every merchant row goes with the table. auth.users and public.profiles are untouched.
--
-- Run the revert of 20260910000000_merchants_contact_and_address.sql first. No statement below uses
-- `cascade`, so a business table added later — one whose foreign key or policy points at this table
-- or at current_merchant_ids() — makes this fail loudly until its own revert has run, rather than
-- being dropped without anyone naming it.

drop function if exists private.current_merchant_ids();

-- Its four policies, the owner_id index, both check constraints and the primary key go with it.
drop table if exists public.merchants;

-- After the table, whose category column is what depends on the type.
drop type if exists public.store_category;

-- Schema `private` stays: 20260902000002_profiles.sql created it, and that migration's revert is the
-- one that removes it.


-- ===== 20260902000003_rls_auto_enable.sql =====

-- Reverts 20260902000003_rls_auto_enable.sql.
--
-- Destroys no data. Tables created afterwards stop getting RLS enabled automatically — which every
-- migration already does explicitly anyway (CLAUDE.md §6.1).
--
-- Run the reverts of every newer migration first; supabase/all-in-one/revert.sql already does.

-- Dropping an event trigger needs superuser, the same as creating one. On a hosted project where the
-- forward migration could not install it there is nothing to drop, so warn and continue rather than
-- stopping the rest of the revert.
do $$
begin
  execute 'drop event trigger if exists ensure_rls';
exception
  when insufficient_privilege then
    raise warning 'ensure_rls not dropped: dropping an event trigger needs superuser.';
end;
$$;

-- After the trigger, which depends on this function. If the trigger exists but could not be dropped
-- above, this fails — correctly, since the function is still in use.
drop function if exists private.rls_auto_enable();


-- ===== 20260902000002_profiles.sql =====

-- Reverts 20260902000002_profiles.sql — the oldest migration, so its revert runs last.
--
-- DESTROYS DATA: every profile row goes with the table. The accounts in auth.users are NOT deleted —
-- this migration never created them — but new signups stop getting a profile, and the RPC behind the
-- Delete account button stops existing.
--
-- Every newer revert must run first. The final `drop schema` fails while any object is still in
-- `private`, and that failure is the check that they did.

drop trigger if exists on_auth_user_created on auth.users;

-- After the trigger that calls it.
drop function if exists private.handle_new_user();

drop function if exists public.delete_current_user();

-- Its three policies and primary key go with it. The foreign key lives on this side, so auth.users
-- itself is untouched.
drop table if exists public.profiles;

-- No `cascade`: if the rls_auto_enable or merchants revert was skipped, their functions are still in
-- here and this fails instead of dropping them unnamed.
drop schema if exists private;
